trigger: none

pool: ado2ghe

steps:
  - script: |
      echo "This script will run forever for testing purposes."
      while true; do
        sleep 60
      done
    displayName: "Infinite Loop Bash Script"